ARG FEDORA_VERSION=38
FROM fedora:${FEDORA_VERSION}

RUN yum -y groupinstall c-development && \
	yum -y install \
		gdb gdb-gdbserver \
		curl \
		less \
		xz \
		libasan \
		libubsan \
		meson \
		ninja-build \
		pkgconf-pkg-config \
		git \
		cmake \
		libffi-devel \
		libgit2-devel

COPY install-criterion.sh ./
RUN bash install-criterion.sh

ENV LD_LIBRARY_PATH=/usr/local/lib64
